export const demo = [  
    {   id: '1',
        demo: 'Leanne Graham'},
    {   id: '2',    
        demo: 'Leanne Graham'},
    {   id: '3',
        demo: 'Leanne Graham'},
    {   id: '4',    
        demo: 'Leanne Graham'},
    {   id: '5',
        demo: 'Leanne Graham'},
    {   id: '6',    
        demo: 'Leanne Graham'},
    {   id: '7',
        demo: 'Leanne Graham'},
    {   id: '8',    
        demo: 'Leanne Graham'},
    {   id: '9',
        demo: 'Leanne Graham'},
    {   id: '10',    
        demo: 'Leanne Graham'},
    ];